### PR TITLE
add_utils_functions

### PR DESCRIPTION
**Pull request by loonghao**
Add a utils function to support addict can be a decorator.

### CODE REVIEW

**Comment by loonghao** [comment]
Hi @mewwts If you have time please help check it. Thanks and Merry Christmas.

**Comment by mewwts** [comment]
Hi @loonghao, sorry for the _way too late_ response. 

If I understand correctly, the purpose of this PR is to create a decorator that will transform the output of a function from a normal `dict` to an addict `Dict`?

What is the benefit of that compared to wrapping the function call in a call to `addict.Dict` like `Dict(function_call())`?

Thanks!

**Comment by loonghao** [comment]
Hi @mewwts, You are right, this a decorator.
It can be very useful as a decorator. It can be converted to `Dict` when the function returns a value.
Can support a single dictionary or list dictionary

```python
 @entity_addict
 def hello_entity_addict():
     return {'test_key': 'test_value'}

 entity = hello_entity_addict()
 print entity.test_key


 @entity_addict
 def hello_entity_addict():
     return [{'test_key': 'test_value'}]

 entitys = hello_entity_addict()
 for entit in entitys:
     print entity.test_key
```

**Comment by mewwts** [comment]
Hey @loonghao, sorry for dropping the ball on this. I think it would be better if you created and maintained a package specifically for this decorator.

**Comment by loonghao** [comment]
Thank you for your suggestion, closing the MR.

**Comment by mewwts** [comment]
Thanks @loonghao, if you end up creating a package, please PR in a section in the bottom of the README where we can point to you project!

**Pull request closed without merging**
