### PR TITLE
Fixed peeking on empty items

### LINKED ISSUE #73: For iPython an addition key '_ipython_canary_method_should_not_exist_' is added.
Under iPython (Python 2.7 & addict 1.1.0), if we have the following code:
```python
from addict import Dict
d = Dict()
print(d.keys())
```
We get the following output:
```
['_ipython_canary_method_should_not_exist_']
```

### PR DESCRIPTION
**Pull request by mewwts**
This should fix #73, #75 and  #26.

### CODE REVIEW

**Comment by Ohjeah** [comment]
@mewwts can you ping me please as soon as you accept this PR and I will update the conda-forge feedstock. :smile:

**Comment by mewwts** [comment]
Yes @Ohjeah.

I'm thinking this will bump `addict` into 2.0.

**Comment by mewwts** [comment]
@burk Could you please review this?

**Comment by burk** [comment]
Really good work! Sorry for being too late to the party 🎉

**Pull request merged**
