### PR TITLE
Return a Dict object instead of {} in __getitem__

### PR DESCRIPTION
**Pull request by thefourtheye**

### CODE REVIEW

**Comment by mewwts** [comment]
Did you mean to close this? The `{}` will be turned in to a `Dict` when set in the addict.Dict, but I guess it would be clearer this way.

**Comment by thefourtheye** [comment]
@mewwts I am working on this. It broke the tests, so I am taking time to understand the actual behavior.

**Comment by mewwts** [comment]
Ok, cool! @thefourtheye :+1:

**Comment by thefourtheye** [comment]
@mewwts I fixed it and I included cosmetic changes now. Please check.

**Comment by mewwts** [comment]
Hey @thefourtheye, thanks for submitting these. I'd like to encourage you to split up this PR into two smaller ones. As far as I can tell, this PR's goal is changing line 101 in addict.py from ```self[name] = {}``` into ```self[name] = Dict()```. The surrounding stylistic changes shadows this. 

Also, I don't see why it's necessary to return on line 105 in (your version of) addict.py.

Thanks again! :+1:

**Comment by mewwts** [comment]
Thanks @thefourtheye!

**Comment by mewwts** [comment]
Also, feel free to submit a PR with the cosmetic changes so that we can discuss them too! Thanks again :+1:

**Pull request merged**
