### PR TITLE
add support for defaultdict

### PR DESCRIPTION
**Pull request by dugres**
I needed to put defaultdicts in addicts, but it didn't work.

### CODE REVIEW

**Comment by mewwts** [comment]
Hi @dugres, thanks for your pull request. 
I see your problem, you were trying to put a defaultdict into an addict, and then all of a sudden the defaultdict was transformed. I wonder if this is also a case of #29, and if it's better solved by not turning dict-instances into addicts if not explicitly told so. What is your take on this?

**Comment by dugres** [comment]
@mewwts : Hi,
I would like better that dicts are turned into addicts by default UNLESS explicitly told not to do so.
By the way, I'm not sure that my patch is the good way to handle defaultdicts (it works for me though), it may be better if they were turned into addicts as well.

**Comment by mewwts** [comment]
Good point @dugres! I'll get some work done on this next week and will figure out a nice way of having default behaviour! Thanks for contributing once again. I'll leave this open, as it might turn out to be a good starting point.

**Comment by mewwts** [comment]
I have not forgotten about this @dugres, I'll be on it soon. Thanks!

**Pull request closed without merging**
